name: ghcp-hackathon
metadata:
  template: ghcp-hackathon@0.0.1
services:
  web:
    host: containerapp
    image: ghcphackathonacr.azurecr.io/hackathon:latest
    language: docker
    project: .
    docker:
      path: Dockerfile
infra:
  provider: bicep
  path: infra
